### PR TITLE
Uniquify stops

### LINKED ISSUE #53: Stops List Broken
#52 and #37 have combined to break the list of stops on the Stops page.

The issue: #37 changed the iteration technique to `collection-repeat`, which demands an array to iterate over.  This was done because it produces a much faster result for large datasets, which we certainly have.  #52 changed the type of the central stopslist to Object, which collection-repeat won't accept.

Additionally, #52 sorts the stops by Name when passing them to the factory (which undoes the geographic sorting we have Avail doing for us now), so changing [this line](https://github.com/umts/pvta-multiplatform/blob/d7e6a78fdbd36d9a17be21aa95bceb7902e9b739/www/templates/stops.html#L7) to use ng-repeat will fix the runtime exception, but we still have the list sorted improperly.

I've reverted #52, because I'd prefer to not have a broken build sitting in Master.

**My question:** what is the best way to do this?  Keeping [the stops list](https://github.com/umts/pvta-multiplatform/blob/a0d95f135624f510862afde6fcb0b26a674d7705/www/js/services.js#L51) as an object means that the Stops page on phones (it works fine in the browser) makes the app unusable, because ng-repeat can't handle the data.

This problem is solved by using an array and `collection-repeat`, but (@dfaulken) does this mean we can't use Underscore's awesome `uniq` method?  If we can use `uniq` on an array, we could just uniquify by Name but keep the sorting as it was when it was delivered by Avail (by removing [this line](https://github.com/umts/pvta-multiplatform/blob/a0d95f135624f510862afde6fcb0b26a674d7705/www/js/services.js#L54)?).

I'm not sure what the best solution is.

### PR DESCRIPTION
**Pull request by petermarathas**
Closes #53

Just needed a couple of small changes to get the StopList to work as an array. Now collection-repeat and _.uniq can work together.

### CODE REVIEW

File: www/js/services.js [hunk 1]
```diff
@@ -48,12 +48,13 @@ angular.module('pvta.services', ['ngResource'])
...
 .factory('StopList', function(){
-  var stopsList = [];
-  var pushToList = function(stop){
-    stopsList.push(stop);
-  };
+  var stopsList = []; 
+
   var pushEntireList = function(list){
-    stopsList = stopsList.concat(list);
+    list = _.uniq(list, true, 'Name');
```
Comment (dfaulken) [inline www/js/services.js]: A second parameter of `true` only works if the list is already sorted by the attribute you're uniquifying by, but that doesn't look like it's the case here ( it was here but it was removed? ).

File: www/js/services.js [hunk 2]
```diff
@@ -48,12 +48,13 @@ angular.module('pvta.services', ['ngResource'])
...
+    _.each(list, function(stop){
```
Comment (akaplo) [inline www/js/services.js]: Since `list` and `stopsList` are both arrays, any reason why we need to loop though it again?  We should just be able to say `stopsList = list`

File: www/js/services.js [hunk 3]
```diff
@@ -48,12 +48,10 @@ angular.module('pvta.services', ['ngResource'])
...
 .factory('StopList', function(){
-  var stopsList = [];
-  var pushToList = function(stop){
-    stopsList.push(stop);
-  };
+  var stopsList = []; 
+
   var pushEntireList = function(list){
-    stopsList = stopsList.concat(list);
+    stopsList = stopsList.concat(_.uniq(list, true, 'Name'));
```
Comment (petermarathas) [inline www/js/services.js:54]: @dfaulken I took out the line that sorts stops by name, because we want to sort them by distance from user instead. However, this line still works, and I believe that's because the stops are ordered by distance, meaning all three Haigis Mall items are next to each other in the array. This is probably all Underscore is looking for when asking if the array is sorted.

**Comment by akaplo** [comment]
I recall hearing that this was going to be discussed during Friday's code review.  Did anything come from it, or should we just merge this in?

**Comment by dfaulken** [comment]
We discussed the edge case of someone standing equidistantly between two stops, and how that could cause unexpected behavior - where sorting stops by distance won't necessarily group them by name. We didn't decide whether that was substantial enough of an edge case to warrant making the sorting algorithm much slower.

**Comment by petermarathas** [comment]
I will merge this. Presumably the worst possible thing that could come from this is an extra stop is in the Stops List. For the time being I can't see how this is worse than a slower algorithm, especially because it will come up so rarely.
